# Generated by Django 4.2.3 on 2023-07-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('registration', models.UUIDField(unique=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('capabilities', models.ManyToManyField(to='fan_api.capability')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actioned', models.BooleanField(default=False)),
                ('queued', models.DateTimeField(auto_now_add=True)),
                ('actioned_time', models.DateTimeField(blank=True, null=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_api.capability')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_api.device')),
            ],
        ),
    ]
